# Generated by Django 3.2.8 on 2021-10-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
