# Generated by Django 3.2.8 on 2021-10-28 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_rename_playlist_name_playlist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='thunmbnail',
            new_name='thumbnail',
        ),
    ]
